# Generated by Django 5.0.2 on 2024-02-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMR_app', '0002_patient_address_patient_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emial',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_time',
            field=models.TimeField(blank=True, default='', null=True),
        ),
    ]
