# Generated by Django 5.0.2 on 2024-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMR_app', '0003_procedure_create_date_procedure_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_date',
            field=models.DateField(blank=True, default='2000-01-02', null=True),
        ),
    ]
