# Generated by Django 5.0.2 on 2024-02-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMR_app', '0004_alter_procedure_procedure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
